name = "CO2System"
uuid = "d1d2487c-1d13-46e4-8493-e7ff3053fc5b"
authors = ["Momme Butenschön"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
